### ISSUE TITLE
errors at npm install

### ISSUE THREAD

**Issue by danbjoseph** [osmlab/osm-meta-api#19]
https://gist.github.com/danbjoseph/6fb39ae979b8e87c55d8
The gist is how far I got and the comment is the error at that point. Any guidance you might be able to provide would be much appreciated. I'm working on an AWS EC2 instance m3.large ubuntu-trusty-14.04-amd64-server.

**Comment by kamicut** [comment]
@danbjoseph It errors out at 'could not find make', could you try this: http://stackoverflow.com/questions/14772508/npm-failed-to-install-time-with-make-not-found-error

**Comment by danbjoseph** [comment]
thanks!

running `sudo apt-get install build-essential` solved the problem of 
```
gyp ERR! build error 
gyp ERR! stack Error: not found: make
```
after `npm install`
